name: Release

on:
  workflow_dispatch:
  push: # TEMPORARY: to test the release workflow
    branches:
      - prepare-1.7.0

jobs:
  cross-compile:
    name: Cross-compile gem for ${{ matrix.platform }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform:
          - "x86_64-linux"
          - "aarch64-linux"
          - "x86_64-darwin"
          - "arm64-darwin"
          - "x64-mingw-ucrt"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby and Rust
        uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: "4.0"
          bundler-cache: true
          cargo-cache: true
          cargo-vendor: true
          cache-version: v1-${{ matrix.platform }}
      - name: Build for ${{ matrix.platform }}
        run:  bundle exec rb-sys-dock --platform ${{ matrix.platform }} --ruby-versions "3.2,3.3,3.4,4.0" --mount-toolchains --build
      - uses: actions/upload-artifact@v6
        with:
          name: gem-${{ matrix.platform }}
          path: pkg/*-${{ matrix.platform }}.gem
  # push:
  #   name: Push gem to RubyGems.org
  #   needs: cross-compile
  #   runs-on: ubuntu-latest

  #   permissions:
  #     id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
  #     contents: write # IMPORTANT: this permission is required for `rake release` to push the release tag

  #   steps:
  #     # Set up
  #     - uses: actions/checkout@v4
  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         bundler-cache: true
  #         ruby-version: 4.0
  #     - name: Set Environment Variables
  #       run: |
  #         version=$(ruby -e 'require_relative "lib/tzf/version"; puts TZF::VERSION')
  #         echo "APP_VERSION=$version" >> $GITHUB_ENV

  #     # Release
  #     - uses: rubygems/release-gem@v1
  #     - uses: actions/download-artifact@v7
  #       with:
  #         path: artifacts
  #     - name: Move gems to pkg directory
  #       run: |
  #         mkdir -p pkg
  #         find artifacts -name "*.gem" -exec mv {} pkg/ \;
  #     - name: Push platform gems
  #       run: |
  #         set -euo pipefail
  #         # Ensure unmatched globs expand to nothing instead of the literal pattern
  #         shopt -s nullglob
  #         # Include only the platform specific gems
  #         for gem in pkg/tzf-*-*.gem; do
  #           gem push "$gem"
  #         done
  #         # Optionally reset nullglob (not strictly necessary in this short script)
  #         shopt -u nullglob

  #     # GitHub release
  #     - uses: ncipollo/release-action@v1
  #       with:
  #         artifacts: "pkg/*.gem"
  #         generateReleaseNotes: true
  #         skipIfReleaseExists: true
  #         tag: ${{ env.APP_VERSION }}
